README.md

Fix markdownlint error

---

.expeditor/buildkite/hugo_lint.sh
.expeditor/config.yml
.expeditor/verify.pipeline.yml

Add expeditor config

---

_vendor/github.com/chef/chef-docs-theme/assets/js/swiftype-config.js
_vendor/github.com/chef/chef-docs-theme/assets/sass/partials/_swiftype_search.scss
_vendor/modules.txt
go.mod
go.sum

Update site theme

---

content/install.md
content/upgrade.md

Update download URL for migration tool

---

content/license/troubleshooting.md
tools/cspell/dictionary.txt

Update email address

---

content/install.md
content/upgrade.md

Remove notes

---

content/kitchen/install.md

Update hab install version

---

content/_index.md

Add text about supported environments

---

_vendor/github.com/chef/chef-docs-theme/assets/sass/_variables.scss
_vendor/github.com/chef/chef-docs-theme/assets/sass/main.scss
_vendor/github.com/chef/chef-docs-theme/assets/sass/partials/_foundation.scss
_vendor/github.com/chef/chef-docs-theme/layouts/_default/sitemap.xml
_vendor/github.com/chef/chef-docs-theme/layouts/partials/version_numbers.html
_vendor/modules.txt
go.mod
go.sum

- https://progresssoftware.atlassian.net/browse/CHEF-19069
- https://github.com/chef/chef-docs-theme/pull/30

Bump Hugo theme

---

content/install.md
content/upgrade.md

Update download text

---

config/_default/menu.toml
config/_default/params.toml
content/agentless/_index.md
content/agentless/resources.md
content/agentless/resources/_index.md
content/agentless/resources/custom.md
content/reusable/md/agentless_custom_resource.md
content/reusable/md/agentless_custom_resource_example.md
content/reusable/md/agentless_summary.md
tools/cspell/dictionary.txt

https://progresssoftware.atlassian.net/wiki/spaces/Infra19/pages/1558151183/Chef+Agentless+Overview
- https://progresssoftware.atlassian.net/browse/CHEF-16133

Add Agentless docs

---

content/_index.md

Cleanup landing page text

---

content/_index.md
content/release_notes.md

Draft RC2 release notes

---

content/_index.md
content/release_notes.md

More release notes edits

---

content/workstation/install/tools.md

Make minor corrections

---

content/workstation/_index.md

Minor corrects

---

content/install/_index.md
content/install/installer/_index.md
content/install/migration_tool/install.md
content/install/migration_tool/install_airgap.md
content/install/migration_tool/reference.md
content/install/migration_tool/upgrade_airgap.md
content/install/migration_tool/upgrade_online.md

More corrections for RC2

---

content/install/migration_tool/upgrade_online.md

Fix migration download-url

---

content/install/migration_tool/reference.md

Fix migration tool CLI example in reference

---

content/install/migration_tool/install.md
content/install/migration_tool/reference.md

Corrections for RC2

---

content/install/migration_tool/install.md
content/install/migration_tool/install_airgap.md
content/install/migration_tool/upgrade_airgap.md
content/install/migration_tool/upgrade_online.md

Add sudo to chef-migrate

---

content/workstation/install/tools.md
content/workstation/install/workstation.md
content/workstation/kitchen/install.md

Minor Hab fixes for RC2 docs

---

LICENSE

- https://choosealicense.com/licenses/cc-by-4.0/
- https://creativecommons.org/licenses/by/4.0/

Add repo license
